[package]
name = "frug_presentation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frug = "0.1.0"
libmath = "0.1.4"